
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

import pandas as pd
import psutil
from subprocess import Popen
from PIL import ImageTk, Image
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Label, Canvas, Entry, Text, Button, PhotoImage, messagebox, filedialog, END
import os,signal,csv,pandas

import tkinter as tk

import SystemSettings as sett
from subprocess import Popen,PIPE
OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/divaskararulmozhi/PycharmProjects/CV_Analyser/build/assets/frame0")
def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)
def checkandGo():
    file = open('name.txt','w')
    if sett.loginCheck(username_entry.get(),password_entry.get(),adap_entry.get())==0:
        window.destroy()
        os.system('python3 gui2.py')
    elif sett.loginCheck(username_entry.get(),password_entry.get(),adap_entry.get())==1:
        file.write(username_entry.get())
        file.close()
        window.destroy()
        os.system('python3 gui1.py')
    else:
        messagebox.showinfo('Login error','Please contact the company for registration')


# Create the main window
window = Tk()
window.title("Chris JP")

# Set window size and disable window resizing
window.geometry("899x529")
window.resizable(False, False)

# Set window background image
bg_image = ImageTk.PhotoImage(Image.open("bg7.png"))
bg_image2 = ImageTk.PhotoImage(Image.open("pbg1.png"))
bg_label = Label(window, image=bg_image)
bg_label.place(x=0, y=0, relwidth=1, relheight=1)

# Create login panel
panel_frame = Label(window, bd=5, relief="groove", image=bg_image2)
panel_frame.place(relx=0.5, rely=0.5, anchor="w")


# Create username label and entry
username_label = Label(panel_frame, text="Username:", font=("GothamBold.ttf", 12))
username_label.grid(row=1, column=0, padx=10, pady=10, sticky="e")
username_entry = Entry(panel_frame, font=("GothamBold.ttf", 12))
username_entry.grid(row=1, column=1, padx=10, pady=10)

# Create password label and entry
password_label = Label(panel_frame, text="Password:", font=("GothamBold.ttf", 12))
password_label.grid(row=2, column=0, padx=10, pady=10, sticky="e")
password_entry = Entry(panel_frame, show="*", font=("GothamBold.ttf", 12))
password_entry.grid(row=2, column=1, padx=10, pady=10)

# Create AD/AP label and entry
adap_label = Label(panel_frame, text="ADMIN/APPLICANT", font=("GothamBold.ttf", 12))
adap_label.grid(row=3, column=0, padx=10, pady=10, sticky="e")
adap_entry = Entry(panel_frame, font=("GothamBold.ttf", 12))
adap_entry.grid(row=3, column=1, padx=10, pady=10)

# Create login button
login_button = Button(panel_frame, text="Login", command=lambda: checkandGo(), font=("GothamBold.ttf", 12))
login_button.grid(row=4, columnspan=2, padx=10, pady=10)

# Start the GUI main loop
window.mainloop()


